name: Compile

on: push

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Compile action
        run: |
          yarn install --frozen-lockfile
          yarn compile
